version: '3.3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 'amin2005'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'
    ports:
      - '1786:5432'
    volumes:
      - my-db:/var/lib/postgresql/data
  adminer:
    image: adminer:latest
    ports:
      - '6271:8080'

volumes:
  my-db:
